SEED: 7
DEBUG: False

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 2048
  EPOCHS: 100
  PATIENCE: 5
  EVAL_MAX_UNITS: None
  VERBOSE: False

CHANGE_DETECTION:
  ENDTOEND: True
  PRETRAINING:
    ENABLED: False
    CFG_NAME: 'popmapping'
    FREEZE_ENCODER: False

MODEL:
  TYPE: 'resnet'
  SIZE: 18
  PRETRAINED: True
  OUT_CHANNELS: 1
  IN_CHANNELS: 4
  LOSS_TYPE: 'L2'

DATALOADER:
  NUM_WORKER: 2
  SHUFFLE: True
  SITES: ['kigali']
  SPECTRAL_BANDS: ['B4', 'B3', 'B2', 'B8']
  YEAR: 2020
  SEASON: 'wet'

AUGMENTATION:
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: False
  RESIZE: False